title: SH Lab
description: >-
  건국대학교 줄기세포재생생명공학과 · 생식세포 및 재생생물학 연구실
lang: ko
url: ""
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  publications:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
